export const RECEIVE_ALL = 'RECEIVE_ALL'
export const FOCUS = 'FOCUS'
export const EDIT = 'EDIT'
export const TITLE_EDIT = 'TITLE_EDIT'
export const SAVE = 'SAVE'
export const TITLE_SAVE = 'TITLE_SAVE'
export const DELETE = 'DELETE'
export const PUBLISH = 'PUBLISH'
export const TITLE_MODIFY = 'TITLE_MODIFY'
export const EXCERPT_MODIFY = 'EXCERPT_MODIFY'
export const LAST_EDIT_TIME = 'LAST_EDIT_TIME'
export const TAG_MODIFY = 'TAG_MODIFY'
export const CATEGORY_MODIFY = 'TAG_MODIFY'
export const CREATE = 'CREATE'
export const IMAGE_MODIFY = 'IMAGE_MODIFY'

export const TOKEN_CREATE = 'TOKEN_CREATE'
export const TOKEN_DELETE = 'TOKEN_DELETE'
